name: run flutter autotests

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.6
      
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Get flutter dependencies.
      - run: flutter pub get
    
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
    
      # Run widget tests for our flutter project.
      - run: flutter test
